### ISSUE TITLE
iguana-workflow should create directories included in the volumes list if they do not exist

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/iguana#18]
Given a list of volumes, Iguana should create the directories that do not exist before trying to bind-mount them:

```yaml
volumes:
  - dbus_run:/var/run/dbus # do nothing, it is a regular volume
  - /etc/NetworkManager:/etc/NetworkManager # ensure that the source directory exists
```

## Rationale

D-Installer backend service needs to access the `/etc/NetworkManager` directory in the `initrd` to copy the configuration files to the installed system at the end of the installation (before unmounting).

However, `/etc/NetworkManager` does not exist when the backend service is started. To avoid adding the empty directory to the Iguana image (and to prevent other similar troubles), `iguana-workflow` will create the directory  (if it does not exist). Beware that we are talking only volumes with an absolute path.

Original discussion: https://github.com/yast/d-installer/pull/398#discussion_r1072232660

**Comment by aaannz** [comment]
Fixed by https://github.com/openSUSE/iguana/pull/27
